var annotated_dup =
[
    [ "bot_player", "classbot__player.html", "classbot__player" ],
    [ "Card_Button", "class_card___button.html", "class_card___button" ],
    [ "Card_Button_Talia", "class_card___button___talia.html", "class_card___button___talia" ],
    [ "card_loader", "classcard__loader.html", "classcard__loader" ],
    [ "deck", "classdeck.html", "classdeck" ],
    [ "deck_loader", "classdeck__loader.html", "classdeck__loader" ],
    [ "deck_saver", "classdeck__saver.html", "classdeck__saver" ],
    [ "decyzjaRuchu", "structdecyzja_ruchu.html", "structdecyzja_ruchu" ],
    [ "efekty_pogodowe", "classefekty__pogodowe.html", "classefekty__pogodowe" ],
    [ "gra", "classgra.html", "classgra" ],
    [ "graveyard", "classgraveyard.html", "classgraveyard" ],
    [ "human_player", "classhuman__player.html", "classhuman__player" ],
    [ "karta", "classkarta.html", "classkarta" ],
    [ "keyword", "classkeyword.html", "classkeyword" ],
    [ "keyword_summon", "classkeyword__summon.html", "classkeyword__summon" ],
    [ "kontener_kart", "classkontener__kart.html", "classkontener__kart" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "nakaz", "structnakaz.html", null ],
    [ "plansza", "classplansza.html", "classplansza" ],
    [ "plansza_linia", "classplansza__linia.html", "classplansza__linia" ],
    [ "player", "classplayer.html", "classplayer" ],
    [ "player_hand", "classplayer__hand.html", "classplayer__hand" ],
    [ "rzedy_enum", "classrzedy__enum.html", "classrzedy__enum" ],
    [ "Stan_Gry", "class_stan___gry.html", "class_stan___gry" ],
    [ "szpieg", "classszpieg.html", "classszpieg" ],
    [ "talia", "classtalia.html", "classtalia" ]
];